console.log("************** Elementos del documento **************")
console.log(window.document)
console.log(document)
console.log(document.head)
console.log(document.body)
console.log(document.documentElement)
console.log(document.characterSet)
console.log(document.title)
console.log(document.links)
console.log(document.images)